/**
 * Email Service — Resend Integration
 *
 * Sends transactional emails after lead capture.
 * Handles both founder-facing confirmation and high-savings Credex CTA.
 */

const { Resend } = require('resend');

let resend = null;

function getClient() {
  if (!resend && process.env.RESEND_API_KEY) {
    resend = new Resend(process.env.RESEND_API_KEY);
  }
  return resend;
}

const FROM = `${process.env.RESEND_FROM_NAME || 'AI Spend Audit'} <${
  process.env.RESEND_FROM_EMAIL || 'audit@aispendaudit.com'
}>`;

/**
 * Sends audit confirmation email to the lead.
 */
async function sendAuditConfirmation({ email, company, totalMonthlySavings, totalAnnualSavings, shareId }) {
  const client = getClient();
  if (!client) {
    console.warn('[emailService] Resend not configured — skipping email');
    return { skipped: true };
  }

  const shareUrl = `${process.env.FRONTEND_URL || 'https://aispendaudit.com'}/audit/${shareId}`;
  const isHighSavings = totalMonthlySavings > 500;

  const htmlBody = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Your AI Spend Audit Results</title>
</head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #f9fafb; margin: 0; padding: 0;">
  <div style="max-width: 580px; margin: 40px auto; background: white; border-radius: 12px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1);">
    
    <!-- Header -->
    <div style="background: linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%); padding: 40px 40px 32px;">
      <h1 style="color: white; margin: 0; font-size: 24px; font-weight: 700;">Your AI Spend Audit</h1>
      <p style="color: rgba(255,255,255,0.85); margin: 8px 0 0; font-size: 15px;">Here's what we found</p>
    </div>

    <!-- Body -->
    <div style="padding: 40px;">
      <p style="color: #374151; font-size: 16px; margin: 0 0 24px;">
        ${company ? `Hi ${company} team,` : 'Hi there,'}
      </p>

      <!-- Savings Summary -->
      <div style="background: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 8px; padding: 24px; margin-bottom: 24px;">
        <p style="color: #166534; font-size: 14px; font-weight: 600; margin: 0 0 8px; text-transform: uppercase; letter-spacing: 0.05em;">Potential Savings Identified</p>
        <p style="color: #15803d; font-size: 36px; font-weight: 800; margin: 0;">${totalMonthlySavings > 0 ? `$${totalMonthlySavings.toLocaleString()}/mo` : 'Already optimized!'}</p>
        ${totalAnnualSavings > 0 ? `<p style="color: #166534; font-size: 14px; margin: 4px 0 0;">That's <strong>$${totalAnnualSavings.toLocaleString()} per year</strong> you could be saving</p>` : ''}
      </div>

      ${
        isHighSavings
          ? `
      <!-- High Savings CTA -->
      <div style="background: #faf5ff; border: 1px solid #e9d5ff; border-radius: 8px; padding: 24px; margin-bottom: 24px;">
        <p style="color: #6b21a8; font-size: 15px; font-weight: 600; margin: 0 0 8px;">🚀 High Savings Alert</p>
        <p style="color: #7c3aed; font-size: 14px; margin: 0 0 16px;">
          With over $${totalMonthlySavings.toLocaleString()}/month in potential savings, your team could benefit from a dedicated AI infrastructure review. 
          The Credex team specializes in helping startups optimize their AI spend.
        </p>
        <a href="https://credex.ai?ref=ai-spend-audit" style="display: inline-block; background: #7c3aed; color: white; text-decoration: none; padding: 12px 24px; border-radius: 6px; font-weight: 600; font-size: 14px;">
          Schedule a Free Consultation →
        </a>
      </div>`
          : ''
      }

      <p style="color: #374151; font-size: 15px; margin: 0 0 20px;">
        View your full audit report with all recommendations:
      </p>

      <a href="${shareUrl}" style="display: inline-block; background: #6366f1; color: white; text-decoration: none; padding: 14px 28px; border-radius: 8px; font-weight: 600; font-size: 15px; margin-bottom: 24px;">
        View My Audit Report →
      </a>

      <p style="color: #6b7280; font-size: 13px; margin: 24px 0 0; border-top: 1px solid #f3f4f6; padding-top: 24px;">
        This audit was generated by AI Spend Audit. Pricing data is verified from official vendor pages.
        <br>You're receiving this because you requested an audit at aispendaudit.com.
      </p>
    </div>
  </div>
</body>
</html>
  `.trim();

  try {
    const result = await client.emails.send({
      from: FROM,
      to: email,
      subject: `Your AI spend audit: ${totalMonthlySavings > 0 ? `$${totalMonthlySavings}/mo in savings found` : 'Your stack is optimized'}`,
      html: htmlBody,
    });
    return { success: true, id: result.id };
  } catch (error) {
    console.error('[emailService] Failed to send email:', error.message);
    return { success: false, error: error.message };
  }
}

module.exports = { sendAuditConfirmation };
